<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
       



        // const f1=()=>{
        //     return new Promise((resolve , reject)=>{
        //     // console.log("function 1");
        //     reject("something went wrong") 
        //     });
        // };
        //  const f2=()=>{
        //         console.log("function 2");

        // }
        // const f3= async()=>{
        //     try{
        //     let n1 = await f1(); //await: it wait for f1 function to complete
        //     f2(n1);}
        //     catch(err)
        //     {
        //         console.log(err)
        //     }
        // }
        // f3();
        // f1()
        // .then (() => f2())
        // .catch ((err) => console.log(err));

        //.then is used only when a function returns a promise ex: return new Promise(resolve , reject) , return()
        


        //transactions , executes seq 
        // const makePayment = () =>{
        //     return new Promise ((resolve , reject)=>{
        //         setTimeout(()=>{
        //             let err= false;
        //             if(!err)resolve();
        //             else reject ("payment error");
        //         }, 5000);
        //     });
        // };

        // const sentNotification =() =>{
        //     console.log("Order has been proceessed");
        // };

    //     const sendEmail =() =>{
    //         console.log("Email :Order has been processed");
    //     };

    //     const sendMessage =() =>{
    //         console.log("message : order has been processed");
    //     };

    //     makePayment()
    //     .then (()=> sendEmail())
    //     .then(()=> sendMessage())
    // .catch((err) => console.log(err));

        //promise
        const f1 =(v) =>{
            return new Promise((resolve , reject)=>{
                setTimeout(()=>{
                    if(v>0) resolve(5)
                    else reject ("Something went wrong");  //we use reject to detect errors 
                },5000)
                

            });
        }//payment function

        const f2 =(x)=>{
            console.log(x+6);
        }; //notification function

        f1(0).then((a )=>f2(a))
        .catch ((err)=>console.log(err));

        //callback
        // const f1 =(fnc) => {
        //     setTimeout(()=>{
        //         fnc(5);
        //     },5000);
        // };
        // const f2 =(a)=>{
        //     console.log(a+10);
        // };
        // f1(f2);



        //asynchronous : occuring at the same time
        // const f1=()=>{
        //     setTimeout(()=>{
        //         return 5
        //     }, 5000);
            
        // };
        // const f2 =(a) =>{
        //     console.log(a+10);
        // };
        // let n1 = f1(); //if takes 5 sec
        // f2(n1); // then this will throw an erroe

    </script>
    
</body>
</html>